# Generated by Django 5.0.7 on 2024-07-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='speciality',
            field=models.CharField(default='none', max_length=125),
        ),
    ]
